# Generated by Django 6.0.4 on 2026-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PRINCIPLE_ADMIN', 'Principle Admin'), ('ADMIN', 'Admin'), ('ACADEMIC_ADMIN', 'Academic Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ACCOUNTANT', 'Accountant')], default='STUDENT', max_length=20),
        ),
    ]
