# Generated by Django 6.0.4 on 2026-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('classroom', 'roll_number')},
        ),
    ]
